# Generated by Django 5.1.1 on 2024-09-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_daycare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daycare',
            old_name='stree_address',
            new_name='street_address',
        ),
    ]
