# Generated by Django 5.1.1 on 2024-09-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_stree_address_daycare_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='daycares',
            field=models.ManyToManyField(blank=True, to='core.daycare'),
        ),
    ]
