# Generated by Django 5.1.1 on 2024-09-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staffprofile_daycares'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycare',
            name='pet_type',
            field=models.IntegerField(choices=[(1, 'dog'), (2, 'cat'), (3, 'bird'), (4, 'fish'), (5, 'reptile')], default=1),
            preserve_default=False,
        ),
    ]
