# Generated by Django 5.1.1 on 2024-09-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_daycare_pet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daycare',
            name='pet_type',
        ),
        migrations.AddField(
            model_name='daycare',
            name='pet_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
