# Generated by Django 5.1.1 on 2024-09-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_daycare_pet_type_daycare_pet_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daycare',
            name='pet_types',
        ),
    ]
