# Generated by Django 5.1.1 on 2024-09-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_daycare_pet_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycare',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daycare',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
