# Generated by Django 5.1.1 on 2024-09-09 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_openinghours_daycare_opening_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daycare',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='openinghours',
            name='daycare',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
            preserve_default=False,
        ),
    ]
