# Generated by Django 5.1.1 on 2024-09-09 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_daycare_opening_hours_openinghours_daycare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='days',
        ),
        migrations.AddField(
            model_name='openinghours',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='daycare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='core.daycare'),
        ),
    ]
