# Generated by Django 5.1.1 on 2024-09-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_openinghours_days_openinghours_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='from_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='to_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
