# Generated by Django 5.1.1 on 2024-09-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycare',
            name='pet_types',
            field=models.JSONField(default=list),
        ),
    ]
