# Generated by Django 5.1.1 on 2024-09-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_staffunavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
