# Generated by Django 5.1.1 on 2024-09-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_roster_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffunavailability',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
