# Generated by Django 5.1.1 on 2024-09-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_pet_petnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='customers',
            new_name='owner',
        ),
    ]
