# Generated by Django 5.1.1 on 2024-09-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_customers_pet_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='owner',
            new_name='customers',
        ),
    ]
