# Generated by Django 5.1.1 on 2024-09-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_owner_pet_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='invite_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
