# Generated by Django 5.1.1 on 2024-10-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_booking_checked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='recurrence',
            field=models.BooleanField(default=False),
        ),
    ]
