# Generated by Django 5.1.1 on 2024-10-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_blacklistedpet'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedpet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
