# Generated by Django 5.1.1 on 2024-10-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_booking_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
