# Generated by Django 5.1.1 on 2024-10-16 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_openinghours_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_waitlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='waitlist_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_notified', models.BooleanField(default=False)),
                ('waitlisted_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
            ],
        ),
    ]
