# Generated by Django 5.1.1 on 2024-10-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_booking_is_waitlist_booking_waitlist_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='customer_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
