# Generated by Django 5.1.1 on 2024-10-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_waitlist_customer_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
